# Site settings
title: "CNN Cancer Detection"
description: "Deep-Wide architecture & Data manipulation"

# Build settings
markdown: kramdown
theme: minima

# Minima theme settings
minima:
  skin: dark # Options: "classic", "solarized", or "dark"
  custom_css: styles.css
  social_links:
    github: "https://github.com/LilaShiba/"
    linkedin: "https://www.linkedin.com/in/shibawizard/"

# Exclude specific files or directories from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle
  - vendor/cache
  - vendor/gems
  - vendor/ruby

# Plugins
plugins:
  - jekyll-feed
